appVersion: ""
hostname: kv.ijmacd.com
mariadb:
  auth:
    database: kv
    username: kv_user
  initdbScriptsConfigMap: kv-store-mariadb-init
  primary:
    resources:
      requests:
        memory: 256Mi
        cpu: 25m
      limits:
        memory: 256Mi
web:
  replicaCount: 1
  repository:
    image: docker.io/ijmacd/kv-store
    tag: ""
  smtp:
    server: email-smtp.us-east-1.amazonaws.com
    user: AKIAWKM4MGHVDE3VTL5K
  existingSecret:
  ingress:
    enabled: false
  gateway:
    enabled: true
    parentRef:
      name: gateway
      namespace: default
      sectionName: https
  tls:
    enabled: false
  local:
    enabled: false
  resources:
    requests:
      memory: 26Mi
      cpu: 5m
    limits:
      memory: 26Mi
