appVersion: ""
hostname: kv.ijmacd.com
postgresql:
  enabled: true
  auth:
    database: kv
    username: kv_user
  primary:
    initdb:
      scriptsConfigMap: kv-store-postgresql-init
mariadb:
  enabled: false
  auth:
    database: kv
    username: kv_user
  initdbScriptsConfigMap: kv-store-mariadb-init
  primary:
    resources:
      requests:
        memory: 108Mi
        cpu: 25m
      limits:
        memory: 108Mi
web:
  replicaCount: 1
  repository:
    image: docker.io/ijmacd/kv-store
    tag: ""
  smtp:
    server: email-smtp.us-east-1.amazonaws.com
    user: AKIAWKM4MGHVDE3VTL5K
  existingSecret:
  tls:
    enabled: false
  local:
    enabled: false
  extraEnv: []
  resources:
    requests:
      memory: 26Mi
      cpu: 5m
    limits:
      memory: 26Mi
