apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-web'
  labels:
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/version: '{{ .Chart.Version }}'
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web
        app.kubernetes.io/instance: '{{ .Release.Name }}'
    spec:
      containers:
        - name: web
          image: '{{ .Values.web.repository.image }}{{ if ne .Values.appVersion "" }}:{{ .Values.appVersion }}{{ end }}'
          env:
            - name: DATABASE_DSN
              value: mysql:host={{ .Release.Name }}-mariadb;dbname={{ .Values.mariadb.auth.database }};charset=utf8mb4
            - name: DATABASE_USER
              value: {{ .Values.mariadb.auth.username }}
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb
                  key: mariadb-password
            - name: SMTP_SERVER
              value: {{ .Values.web.smtp.server }}
            - name: SMTP_USER
              value: {{ .Values.web.smtp.user }}
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-web
                  key: smtp-password
          {{ if .Values.web.local.enabled }}
          volumeMounts:
            - name: src
              mountPath: /var/www/html
          {{ end }}
          ports:
            - name: web
              containerPort: 80
      {{ if .Values.web.local.enabled }}
      volumes:
        - name: src
          hostPath:
            path: /ijmacd/kv-store/src
      {{ end }}
